### ISSUE TITLE
race mechanic: waiting time before race initiates does not work in multiplayer

### ISSUE THREAD

**Issue by KristineSaroka** [DkITJamesFarrell/GoRo#47]
### The Issue:
When initiating a race, with a capacity greater than the amount of players set to two (myself being the only player in the room) the race countdown begins straight away, without any wait time. Error occurs only in multiplayer mode.

### The Expected Functionality:
Once a race is initiated, there is a set wait time that will activate upon the race initiation. If the capacity is greater than one, the wait time will activate to allow other players to take part in this race session. Only after the set wait time has passed, will the player be spawned onto the race track and the countdown be initiated.

### Steps to Recreate Issue:
1.Start game and choose single-player/ multi-player mode
2.Once loaded into scene, press menu button and start a race 
3.You will notice that you will be spawned onto the race track straight away followed by getting a countdown displayed to you.

### Version of the project at which the issue was noticed
Issue identified within the recent master branch commit number: fce11a1

**Comment by DkITJamesFarrell** [comment]
Addressed in commit 2703178f6b3dd814c185884452bd8e5f7c3aa124.
