### ISSUE TITLE
race mechanic: multiplayer race not displaying signs of connection

### ISSUE THREAD

**Issue by KristineSaroka** [DkITJamesFarrell/GoRo#49]
### The Issue:
This issue is multiplayer-specific. In general, when joining a multiplayer room and selecting to start a race, and having another player join in, the race works as expected until a player reaches the finish line. At this point, the race does not continue, for the other participants who have not yet reached the finish line, all of them receive the message that they came first in the race.

### The Expected Functionality:
In multiplayer, once a player crosses the finish line, they are expected to be spawned out of the race, while the other participants would continue this race, and of course the player's should get notified the correct places they got in the race they partook in after completing it.

### Steps to Recreate Issue:
1.Start game and choose multi-player mode
2.Create a room and wait for companion to join room
3.Once both players are loaded in, press menu button, and select "Start a Race"
4.Partake in race
5.See what happens to the player that has not yet completed the race, one of the other players crosses the finish line on their last lap

### Version of the project at which the issue was noticed
Issue identified within the recent master branch commit number: 61a7891c01101b98ccec6a20dd533992965f4c2b

**Comment by DkITJamesFarrell** [comment]
Addressed in commit 2703178f6b3dd814c185884452bd8e5f7c3aa124.
